viabana_nuevo/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace viabana_nuevo.Models
{
    public class Categoria
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string UrlImagen { get; set; }
    }
}

viabana_nuevo/Models/Concepto.cs
using System.Collections.Generic;

namespace viabana_nuevo.Models
{
    public class Concepto
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public float Valor { get; set; }
        public Enumeraciones.TipoConcepto TipoConcepto { get; set; }
        public Enumeraciones.Unidad Unidad { get; set; }
        public Enumeraciones.Efecto Efecto { get; set; }
        //public virtual List<ConceptoCategoriaEmpleado> ConceptoCategoriaEmpleados { get; set; }

    }
}

viabana_nuevo/Controllers/ConceptosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using viabana_nuevo.Models;
using viabana_nuevo.Servicios;

namespace viabana_nuevo.Controllers
{
    public class ViewModelCategoriaDeEmpleado
    {
        public int IdCategoria { get; set; }
        public string DescripcionCategoria { get; set; }
        public float MontoSueldoBasico { get; set; }
        public List<Concepto> ConceptosDeSueldo { get; set; }
        
    }
    public class ConceptosController : Controller
    {
        private readonly IRepositorio<Concepto> _repoConcepto;
        private readonly IRepositorio<CategoriaEmpleado> _repoCategoria;
        private readonly IRepositorioConceptoCategoria _repoConceptoCategoria;

        public ConceptosController(IRepositorio<Concepto> repoConcepto, IRepositorio<CategoriaEmpleado> repoCategoria, IRepositorioConceptoCategoria repoConceptoCategoria)
        {
            this._repoConcepto = repoConcepto;
            this._repoCategoria = repoCategoria;
            this._repoConceptoCategoria = repoConceptoCategoria;
        }
        // GET: Conceptos
        public ActionResult Categorias()
        {
            var listaCategorias = _repoCategoria.Listar();
            //var listaCategorias = GeneradorDatos.GenerarCategoriasEmpleados();
            return View(listaCategorias);
        }

        public ActionResult VerConceptosDeCategoria(int id)
        {
            var listaCategorias = GeneradorDatos.GenerarCategoriasEmpleados();
            var categoria = listaCategorias.Find(x => x.Id == id);
            return View("Partials/_VerConceptosDeCategoria", categoria);
        }

        public ActionResult VerConceptos()
        {
            var listaConceptos = _repoConcepto.Listar();
            //var listaConceptos = GeneradorDatos.GenerarConceptos().Concat(GeneradorDatos.GenerarNovedades()).ToList();
            return View(listaConceptos);
        }

        [HttpGet]
        public ActionResult AgregarNuevoConcepto()
        {
            ViewBag.TipoConcepto = Enumeraciones.TipoConcepto.Sueldo;
            return View();
        }

        [HttpPost]
        public ActionResult AgregarNuevoConcepto(Concepto concepto)
        {
            _repoConcepto.Guardar(concepto);
            return RedirectToAction("VerConceptos");
        }

        [HttpGet]
        public ActionResult AgregarNuevaCategoria()
        {
            var modelo = new ViewModelCategoriaDeEmpleado();
            modelo.ConceptosDeSueldo = /*GeneradorDatos.GenerarConceptos();*/
                _repoConcepto.Listar();
            return View(modelo);
        }

        [HttpPost]
        public ActionResult AgregarNuevaCategoria(ViewModelCategoriaDeEmpleado modelo)
        {
            if(modelo.ConceptosDeSueldo != null)
            {
                var categoria = new CategoriaEmpleado();
                categoria.Descripcion = modelo.DescripcionCategoria;
                categoria.SueldoBasico = modelo.MontoSueldoBasico;
                _repoCategoria.Guardar(categoria);
                categoria.Conceptos = modelo.ConceptosDeSueldo;
                _repoConceptoCategoria.AsociarConceptosACategoria(categoria);
                return RedirectToAction("Categorias");
            }
            else
            {
                return View(modelo);
            }

        }

        [HttpGet]
        public ActionResult EditarCategoria(int id)
        {
            var categoria = _repoCategoria.BuscarPorId(id);
            var modelo = new ViewModelCategoriaDeEmpleado();
            var conceptos = new List<Concepto>();
            var items = _repoConceptoCategoria.BuscarConceptosDeCategoria(id);
            foreach(var item in items) 
            {
                conceptos.Add(item.Concepto);
            }
            modelo.DescripcionCategoria = categoria.Descripcion;
            modelo.MontoSueldoBasico = categoria.SueldoBasico;
            modelo.ConceptosDeSueldo = conceptos;
            modelo.IdCategoria = id;

            return View(modelo);
        }

        [HttpPost]
        public ActionResult EditarCategoria(ViewModelCategoriaDeEmpleado modelo, int id)
        {
            var categoria = new CategoriaEmpleado();
            var items = new List<ConceptoCategoriaEmpleado>();
            categoria.Id = id;
            categoria.Descripcion = modelo.DescripcionCategoria;
            categoria.SueldoBasico = modelo.MontoSueldoBasico;
            _repoCategoria.Actualizar(categoria);
            _repoConceptoCategoria.Actualizar(modelo.ConceptosDeSueldo, id);
            return RedirectToAction("VerConceptos");
        }

        public ActionResult EliminarCategoria(int id)
        {
            _repoCategoria.Eliminar(id);
            _repoConceptoCategoria.Eliminar(id);
            return RedirectToAction("Categorias");
        }

        [HttpGet]
        public ActionResult EditarConcepto(int id)
        {
            var modelo = _repoConcepto.BuscarPorId(id);
            return View(modelo);
        }

        [HttpPost]
        public ActionResult EditarConcepto(Concepto concepto)
        {
            _repoConcepto.Actualizar(concepto);
            return RedirectToAction("VerConceptos");
        }

        public ActionResult EliminarConcepto(int id)
        {
            _repoConcepto.Eliminar(id);
            return RedirectToAction("VerConceptos");
        }
    }
}

viabana_nuevo/Views/Conceptos/AgregarNuevaCategoria.cshtml
@model viabana_nuevo.Controllers.ViewModelCategoriaDeEmpleado



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AgregarNuevaCategoria</title>
</head>
<body>
    <div class="general-pages">
            <div class="form-horizontal col-lg-7">
                <h2>Nueva Categoría de empleado</h2>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DescripcionCategoria, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.DescripcionCategoria, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DescripcionCategoria, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="form-group">
                    @Html.LabelFor(model => model.Categoria.Conceptos, htmlAttributes:  new { @class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.SueldoBasico, Model.SueldoBasico, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.MontoSueldoBasico, "Sueldo (por día)", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.MontoSueldoBasico, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ConceptosDeSueldo, "Conceptos de sueldo", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <select class="form-control" id="ConceptosDeSueldo">
                            @foreach (var concepto in Model.ConceptosDeSueldo)
                            {
                                <option value="@concepto.Id" 
                                        data-valor="@concepto.Valor"
                                        data-unidad="@concepto.Unidad">@concepto.Descripcion</option>
                            }
                        </select>
                        <button class="btn btn-primary" id="agregarConcepto" style="margin-top: 10px">Agregar Concepto</button>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <input type="submit" value="Crear categoría" class="btn btn-default" id="crearCategoria" data-url="@Url.Action("AgregarNuevaCategoria", "Conceptos")"/>
                        <button class="btn btn-danger" style="margin-top: 10px" onclick="location.href='@Url.Action("Categorias", "Conceptos")'">Volver</button>
                    </div>
                </div>

            </div>
            <div class="col-lg-5" style="height: 400px; overflow-y: auto; margin-top: 7%">
                <table class="table table-hover" id="tablaConceptos">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Descripción</th>
                            <th>Valor</th>
                            <th>Unidad</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
    </div>
</body>
</html>

viabana_nuevo/Views/Conceptos/AgregarNuevoConcepto.cshtml
<!DOCTYPE html>
@model viabana_nuevo.Models.Concepto

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AgregarNuevoConcepto</title>
</head>
<body>
    <div class="general-pages">
        @using (Html.BeginForm("AgregarNuevoConcepto", "Conceptos", FormMethod.Post))
        {
            @Html.AntiForgeryToken();
            
            <h2>Nuevo Concepto de Sueldo/Novedad</h2>
            <div class="form-horizontal" style="margin-top: 5%">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, "Nombre del concepto", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @*@Html.ValidationMessageFor(model => model.Descripcion, "Ingrese un nombre para el concepto", new { @class = "text-danger"})*@
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Efecto, htmlAttributes: new { @class = "control-label col-md-2"})
                    <div>
                        @Html.EnumDropDownListFor(model => model.Efecto, htmlAttributes: new {@class = "form-control"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoConcepto, htmlAttributes: new { @class = "control-label col-md-2"})
                    <div>
                        @Html.EnumDropDownListFor(model=> model.TipoConcepto, htmlAttributes: new { @class= "form-control"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Unidad, htmlAttributes: new { @class = "control-label col-md-2"})
                    <div>
                        @Html.EnumDropDownListFor(model => model.Unidad, htmlAttributes: new { @class = "form-control"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2"})
                    <div>
                        @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control"} })
                    </div>
                </div>
                <div class="form-group">
                    <input type="button" class="btn btn-danger" onclick="location.href='@Url.Action("VerConceptos","Conceptos")'" value="Volver" style="margin-left: 25%"/>
                    <input type="submit" class="btn btn-default" value="Enviar" style="margin-left: 5%"/>
                </div>

            </div>
        }
    </div>
</body>
</html>

viabana_nuevo/Views/Conceptos/Categorias.cshtml
<!DOCTYPE html>
@model List<viabana_nuevo.Models.CategoriaEmpleado>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Conceptos</title>
</head>
<body>
    <div class="general-pages">
        <h2>Categorías de empleados</h2>
        <div class="col-lg-7" style="height: 250px; overflow-y:auto">
            <table class="table table-hover" style="width: 95%; position: absolute">
                <thead>
                    <tr>
                        <td><strong>Código</strong></td>
                        <td><strong>Descripción</strong></td>
                        <td><strong>Sueldo Básico</strong></td>
                        <td><strong>Expandir</strong></td>
                        <td><strong>Editar</strong></td>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var categoria in Model)
                    {
                        <tr>
                            <td>@categoria.Id</td>
                            <td>@categoria.Descripcion</td>
                            <td>@categoria.SueldoBasico</td>
                            <td><span class="glyphicon glyphicon-expand verConceptos" data-url="@Url.Action("VerConceptosDeCategoria", "Conceptos", new { id = categoria.Id})"></span></td>
                            <td><span class="glyphicon glyphicon-edit editarCategoria" onclick="location.href='@Url.Action("EditarCategoria", "Conceptos", new { id = categoria.Id})'"></span></td>
                            <td><span class="glyphicon glyphicon-erase" onclick="location.href='@Url.Action("EliminarCategoria", "Conceptos", new { id = categoria.Id})'"></span></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-5">
            <button class="btn btn-info" style="float:left; margin-top: 5%" onclick="location.href='@Url.Action("AgregarNuevaCategoria", "Conceptos")'">Agregar Categoria</button>
            <button class="btn btn-info" style="float:left; margin-top: 5%; margin-left:5%" onclick="location.href='@Url.Action("VerConceptos", "Conceptos")'">Ver Conceptos y Novedades</button>
        </div>
        <div class="col-lg-12" id="listaConceptos">

        </div>
    </div>
</body>
</html>

viabana_nuevo/Views/Conceptos/EditarCategoria.cshtml
@model viabana_nuevo.Controllers.ViewModelCategoriaDeEmpleado
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditarCategoria</title>
</head>
<body>
    <div class="general-pages">
    <div class="form-horizontal col-lg-7">
        <h2>Editar categoría @Model.DescripcionCategoria</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionCategoria, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.DescripcionCategoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionCategoria, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MontoSueldoBasico, "Sueldo (por día)", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.MontoSueldoBasico, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConceptosDeSueldo, "Conceptos de sueldo", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-4">
                <select class="form-control" id="ConceptosDeSueldo">
                    @foreach (var concepto in Model.ConceptosDeSueldo)
                    {
                        <option value="@concepto.Id"
                                data-valor="@concepto.Valor"
                                data-unidad="@concepto.Unidad">
                            @concepto.Descripcion
                            </option>
                        }
                </select>
                <button class="btn btn-primary" id="agregarConcepto" style="margin-top: 10px">Agregar Concepto</button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                <input type="submit" value="Modificar categoría" class="btn btn-default" id="crearCategoria" data-url="@Url.Action("EditarCategoria", "Conceptos", new { id = Model.IdCategoria})" />
                <button class="btn btn-danger" style="margin-top: 10px" onclick="location.href='@Url.Action("Categorias", "Conceptos")'">Volver</button>
            </div>
        </div>

    </div>
    <div class="col-lg-5" style="height: 400px; overflow-y: auto; margin-top: 7%">
        <table class="table table-hover" id="tablaConceptos">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Descripción</th>
                    <th>Valor</th>
                    <th>Unidad</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach(var concepto in Model.ConceptosDeSueldo)
                    {
                        <tr>
                            <td id="codigo">@concepto.Id</td>
                            <td>@concepto.Descripcion</td>
                            <td>@concepto.Valor</td>
                            <td>@concepto.Unidad</td>
                            <td><span class='glyphicon glyphicon-erase btnEliminar' style='color: #FF6631'></span></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    </div>
</body>
</html>

viabana_nuevo/Views/Conceptos/EditarConcepto.cshtml
@model viabana_nuevo.Models.Concepto

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditarConcepto</title>
</head>
<body>
    <div class="general-pages">
        @using (Html.BeginForm("EditarConcepto", "Conceptos", FormMethod.Post))
        {
            @Html.AntiForgeryToken();

            <h2>Nuevo Concepto de Sueldo/Novedad</h2>
            <div class="form-horizontal" style="margin-top: 5%">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, "Nombre del concepto", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @*@Html.ValidationMessageFor(model => model.Descripcion, "Ingrese un nombre para el concepto", new { @class = "text-danger"})*@
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Efecto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Efecto, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoConcepto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.TipoConcepto, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Unidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Unidad, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    <input type="button" class="btn btn-danger" onclick="location.href='@Url.Action("VerConceptos","Conceptos")'" value="Volver" style="margin-left: 25%" />
                    <input type="submit" class="btn btn-default" value="Guardar" style="margin-left: 5%" />
                </div>

            </div>
        }
    </div>
</body>
</html>

viabana_nuevo/Views/Conceptos/VerConceptos.cshtml
@model List<viabana_nuevo.Models.Concepto>

<!DOCTYPE html> 
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>VerConceptos</title>
</head>
<body>
    <div class="general-pages">
        <h2>Lista de conceptos</h2>
        <div class="col-lg-7" style="height:250px; overflow-y: auto">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td><strong>Código</strong></td>
                        <td><strong>Descripcion</strong></td>
                        <td><strong>Valor</strong></td>
                        <td><strong>Unidad</strong></td>
                        <td><strong>Editar</strong></td>
                        <td><strong>Eliminar</strong></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var concepto in Model)
                    {
                        if (concepto.TipoConcepto.ToString() == "Sueldo")
                        {
                            <tr>
                                <td>@concepto.Id</td>
                                <td>@concepto.Descripcion</td>
                                <td>@concepto.Valor</td>
                                <td>@concepto.Unidad</td>
                                <td><span class="glyphicon glyphicon-edit btnEditar" onclick="location.href='@Url.Action("EditarConcepto","Conceptos", new { id = concepto.Id})'" style="color: darkslateblue"></span></td>
                                <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("EliminarConcepto", "Conceptos", new { id = concepto.Id})'" style="color: #f72a0e"></span></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-4" style="height: 250px">
            <button class="btn btn-primary" style="margin-left: 5%; margin-top:15%;" onclick="location.href='@Url.Action("AgregarNuevoConcepto","Conceptos")'">Agregar Nuevo Concepto o Novedad</button>
        </div>
        
        <div class="col-lg-12">
            <h2>Lista de Novedades</h2>
        </div>
        <div class="col-lg-7" style="height:250px; overflow-y: auto">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td><strong>Código</strong></td>
                        <td><strong>Descripcion</strong></td>
                        <td><strong>Valor</strong></td>
                        <td><strong>Unidad</strong></td>
                        <td><strong>Editar</strong></td>
                        <td><strong>Eliminar</strong></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var concepto in Model)
                    {
                        if (concepto.TipoConcepto.ToString() == "Novedad")
                        {
                            <tr>
                                <td>@concepto.Id</td>
                                <td>@concepto.Descripcion</td>
                                <td>@concepto.Valor</td>
                                <td>@concepto.Unidad</td>
                                <td><span class="glyphicon glyphicon-edit" onclick="location.href='@Url.Action("EditarConcepto","Conceptos", new { id = concepto.Id})'"  style="color: darkslateblue"></span></td>
                                <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("EliminarConcepto", "Conceptos", new { id = concepto.Id})'" style="color: #f72a0e"></span></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>