viabana_nuevo/Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using viabana_nuevo.Models;

namespace viabana_nuevo.Controllers
{
    public class PersonalController : Controller
    {
        // GET: Personal
        public ActionResult Personal()
        {
            var listaEmpleados = GeneradorDatos.GenerarEmpleados();
            return View(listaEmpleados);
        }

        public ActionResult Novedades(int idEmpleado)
        {
            var listaEmpleados = GeneradorDatos.GenerarEmpleados();
            var empleado = listaEmpleados.Find(x => x.Legajo == idEmpleado);
            ViewBag.Empleado = empleado;

            var listaNovedades = GeneradorDatos.GenerarNovedades();

            return View(listaNovedades);
        }

        public ActionResult EditarEmpleado(int idEmpleado)
        {
            var listaEmpleados = GeneradorDatos.GenerarEmpleados();
            var empleado = listaEmpleados.Find(x => x.Legajo == idEmpleado);


            return View(empleado);
        }
    }
}

viabana_nuevo/Views/Personal/EditarEmpleado.cshtml
@model viabana_nuevo.Models.Empleado


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditarEmpleado</title>
</head>
<body>
    <div class="general-pages">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Empleado</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DNI, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Legajo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Legajo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Legajo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaIngreso, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaIngreso, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Estado)
                        @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div>
</body>
</html>

viabana_nuevo/Views/Personal/Novedades.cshtml
<!DOCTYPE html>
@model List<viabana_nuevo.Models.Concepto>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Novedades</title>
</head>
<body>
    <div class="general-pages">
        <h2>Novedades de @ViewBag.Empleado.Nombre @ViewBag.Empleado.Apellido</h2>
        <select>
            @foreach(var novedad in Model)
            {
                <option value="@novedad.Id">@novedad.Descripcion</option>
            }
        </select>
    </div>
</body>
</html>

viabana_nuevo/Views/Personal/Personal.cshtml
<!DOCTYPE html>

@model List<viabana_nuevo.Models.Empleado>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Personal</title>
</head>
<body>
    <div class="general-pages">
        <h2>Lista de empleados</h2>
        <div class="col-lg-12" style="height: 30%">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td><strong>Apellido</strong></td>
                        <td><strong>Nombre</strong></td>
                        <td><strong>Cuenta</strong></td>
                        <td><strong>Fecha de ingreso</strong></td>
                        <td><strong>Categoria</strong></td>
                        <td><strong>Editar</strong></td>
                        <td><strong>Agregar Novedad</strong></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var empleado in Model){
                        <tr>
                            <td>@empleado.Apellido</td>
                            <td>@empleado.Nombre</td>
                            <td></td>
                            <td>@empleado.FechaIngreso</td>
                            <td>@empleado.CategoriaEmpleado.Descripcion</td>
                            <td><a href="@Url.Action("EditarEmpleado", "Personal", new { idEmpleado = empleado.Legajo})"><span class="glyphicon glyphicon-edit editarEmpleado" title="Editar"></span></a></td>
                            <td><a href="@Url.Action("Novedades", "Personal", new { idEmpleado = empleado.Legajo })"><span class="glyphicon glyphicon-plus agregarNovedad" title="Agregar novedad"></span></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-12">
            <h2>Acciones</h2>
            <button class="btn btn-default" onclick="location.href='@Url.Action("Venta", "Venta")'">Editar Categorías</button>
        </div>
    </div>
</body>
</html>