viabana_nuevo/Models/Liquidacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace viabana_nuevo.Models
{
    public class Liquidacion
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public List<DetalleLiquidacion> DetalleLiquidaciones { get; set; }
        public CategoriaEmpleado CategoriaEmpleado { get; set; }
        public DateTime Periodo { get; set; }
        public bool Estado { get; set; }
    }
}

viabana_nuevo/Controllers/LiquidacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using viabana_nuevo.Models;

namespace viabana_nuevo.Controllers
{
    public class DiasTrabajadosEmpleados
    {
        public int Id { get; set; }
        public int DiasTrabajados { get; set; }
    }
    public class ViewModelAgregarLiquidacion
    {
        public string Descripcion { get; set; }
        public DateTime Periodo { get; set; }
        public int CategoriaEmpleado { get; set; }
        public List<CategoriaEmpleado> ListaCategorias { get; set; }
        public List<DiasTrabajadosEmpleados> ListaEmpleados { get; set; }
    }
    public class LiquidacionController : Controller
    {
        // GET: Liquidacion
        public ActionResult Liquidaciones()
        {
            var liquidaciones = GeneradorDatos.GenerarLiquidaciones();
            return View(liquidaciones);
        }

        public ActionResult AgregarLiquidacion()
        {
            var modelo = new ViewModelAgregarLiquidacion();
            modelo.ListaCategorias = GeneradorDatos.GenerarCategoriasEmpleados();
            return View(modelo);
        }

        [HttpPost]
        public ActionResult GuardarLiquidacion(ViewModelAgregarLiquidacion modelo)
        {
            return View();
        }

        public ActionResult ListarEmpleadosALiquidar(int idCategoria)
        {
            var listaEmpleados = GeneradorDatos.GenerarEmpleados().FindAll(empleado => empleado.CategoriaEmpleado.Id == idCategoria);
            return View("Partials/_ListaEmpleadosALiquidar", listaEmpleados);
        }

        public ActionResult VerLiquidacion()
        {
            var modelo = GeneradorDatos.GenerarLiquidaciones()[0];
            return View(modelo);
        }

        public ActionResult MostrarDetalleLiquidacion(int id)
        {
            var detalleLiquidacion = GeneradorDatos.GenerarDetalleLiquidaciones().Find(x => x.Id == id);
            return View("Partials/_MostrarDetalleLiquidacion", detalleLiquidacion);
        }
    }
}

viabana_nuevo/Views/Liquidacion/AgregarLiquidacion.cshtml
@model viabana_nuevo.Controllers.ViewModelAgregarLiquidacion


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AgregarLiquidacion</title>
</head>
<body>
    <div class="general-pages">
        <h2>Nueva Liquidación</h2>
        <div class="col-lg-6">
            <div class="form-group" style="margin-top: 20px">
                <label for="Descripcion" class="control-label col-md-3">Descripción</label>
                <input class="form-control" type="text" id="Descripcion" />
            </div>
            <div class="form-group" style="margin-top: 20px">
                <label for="Descripcion" class="control-label col-md-3">Periodo</label>
                <input class="form-control" type="date" id="Periodo" />
            </div>
            <div class="form-group" style="margin-top: 20px">
                <label for="Categoria" class="control-label col-md-3">Categoria</label>
                <select class="form-control col-md-1" id="Categoria" style="width: 200px">
                    @foreach(var categoria in Model.ListaCategorias)
                    {
                        <option value="@categoria.Id">@categoria.Descripcion</option>
                    }
                </select>
                <button class="btn btn-default" id="cargarEmpleados" style="background-color: #7cffaf; margin-left:10px" data-url="@Url.Action("ListarEmpleadosALiquidar","Liquidacion", new { idCategoria = "param-index" })">Cargar</button>
            </div>
            <button class="btn btn-danger" onclick="location.href='@Url.Action("Liquidaciones", "Liquidacion")'">Volver</button>
            <button class="btn btn-primary" id="btnGuardar" data-url="@Url.Action("GuardarLiquidacion", "Liquidacion")">Guardar</button>
        </div>
        <div class="col-lg-6" id="listaEmpleados">
            
        </div>
    </div>
</body>
</html>

viabana_nuevo/Views/Liquidacion/Liquidaciones.cshtml
@model List<viabana_nuevo.Models.Liquidacion>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Liquidaciones</title>
</head>
<body>
    <div class="general-pages">
        <h2>Liquidaciones</h2>
        <div class="col-lg-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Descripcion</th>
                        <th>Periodo</th>
                        <th>Categoria Liquidada</th>
                        <th>Estado</th>
                        <th>Ver</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var liquidacion in Model)
                    {
                        <tr>
                            <td>@liquidacion.Descripcion</td>
                            <td>@liquidacion.Periodo.Month/@liquidacion.Periodo.Year</td>
                            <td>@liquidacion.CategoriaEmpleado.Descripcion</td>
                            @if (liquidacion.Estado)
                            {
                                <td><p style="color: cornflowerblue">Liquidado</p></td>
                            } else
                            {
                                <td><p style="color: orangered">Pendiente</p></td>
                            }
                            <td><span class="glyphicon glyphicon-eye-open"></span></td>
                        </tr>
                    }
                </tbody>
            </table>
            <button class="btn btn-primary" onclick="location.href='@Url.Action("AgregarLiquidacion", "Liquidacion")'">Agregar Nueva Liquidacion</button>
        </div>
    </div>
</body>
</html>

viabana_nuevo/Views/Liquidacion/VerLiquidacion.cshtml
@model viabana_nuevo.Models.Liquidacion
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>VerLiquidacion</title>
</head>
<body>
    <div class="general-pages">
        <h2>Empleados para liquidar</h2>
        <div class="col-lg-8" style="height: 250px; overflow-y:auto">
            <table class="table table-hover" id="tablaEmpleadosALiquidar">
                <thead>
                    <tr>
                        <th>Apellido</th>
                        <th>Nombre</th>
                        <th>Remuneraciones</th>
                        <th>Descuento</th>
                        <th>Neto</th>
                        <th>Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var detalle in Model.DetalleLiquidaciones)
                    {
                        <tr>
                            <td>@detalle.Empleado.Apellido</td>
                            <td>@detalle.Empleado.Nombre</td>
                            <td>@detalle.TotalLiquidado</td>
                            <td>@detalle.TotalLiquidado</td>
                            <td>@detalle.TotalLiquidado</td>
                            <td><span class="glyphicon glyphicon-eye-open btnVerDetalle" style="color: cornflowerblue" data-url="@Url.Action("MostrarDetalleLiquidacion", "Liquidacion", new { id = detalle.Id})"></span></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">

        </div>
        <div class="col-lg-8" id="detalleLiquidacion">

        </div>
    </div>
</body>
</html>